### DISCUSSION TITLE
TMDb needed for IMDb?

### DISCUSSION THREAD

**Discussion by nhaas** [mza921/Plex-Auto-Collections#184] [Q&A] [answered]
Hello,
I'm trying to get this simple config to work, but running into issues...
```
# config.yml
plex:                                         # Req
  library: Movies                             # Req - Name of Plex library
  library_type: movie                         # Req - Type of Plex library (movie or show)
  token: --redacted--                 # Req - User's Plex authentication token
  url: --redacted--             # Req - URL to access Plex
  sync_mode: sync                             # Opt - Global Sync Mode

collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250&sort=user_rating,desc
    sort_title: "*010"
```

However, it tells me that
```
| Updating collection: IMDb Top 250...
| Sync Mode: sync
| Config Error: imdb_list skipped. tmdb incorrectly configured
```

Am I missing something?
