### DISCUSSION TITLE
Single config for TV and Movies possible?

### DISCUSSION THREAD

**Discussion by PleaseStopAsking** [mza921/Plex-Auto-Collections#204] [Q&A]
I have had no issues using a single config file for each library but wondered if it was possible to unify those into a single config that worked for both tv and movie libraries so that I am not storing the same sensitive strings in multiple files such as Plex and radarr token as well as the tmdb key. It seems as if a new attribute should exist for each collection that would allow you to define which library it was for sure as below but this is just off the top of my head.

Is this sort of config even possible?

Thanks in advance

```

secret:
  plex_token: exampletoken

plex:
  library: Movies
  library_type: movie
  sync_mode: sync
  token: plex_token
  url: http://192.168.4.46:32400

plex:
  library: TV Shows
  library_type: show
  sync_mode: sync
  token: plex_token
  url: http://192.168.4.46:32400

collections:
  3 Ninjas:
    poster: https://www.themoviedb.org/t/p/original/kTRDNxSlNSE7n9cF9W2xx9frs3d.jpg
    tmdb_collection: 71458
    tmdb_summary: 71458
    plex_library: Movies

  ABC:
    collection_order: alpha
    tmdb_network: 2
    plex_library: TV Shows
```

**Comment by meisnate12** [comment]


**Reply by PleaseStopAsking** [reply]
Then I must be doing something wrong it seems. I have two config files (config-tv.yml and config-movie.yml) and within each one, I have to define my connection to plex and tmdb with the required keys. Each one is tailored to toward the specific library in plex so the only real difference in the two files is plex library type, library name and collections content.

I then need to pass in the respective config file based on which library I want to interact with.

**config-movie.yml**
```
collections:
  3 Ninjas:
    poster: https://www.themoviedb.org/t/p/original/kTRDNxSlNSE7n9cF9W2xx9frs3d.jpg
    tmdb_collection: 71458
    tmdb_summary: 71458
plex:
  library: Movies
  library_type: movie
  sync_mode: sync
  token: removed
  url: http://192.168.4.46:32400
radarr:
  add_to_radarr: true
  quality_profile_id: 5
  root_folder_path: /data/8d19a07a-03d5-45f1-85dc-ccd49430f386/data/media/Movies
  search_movie: false
  token: removed
  url: http://192.168.4.46:7878
  version: v3
tmdb:
  apikey: removed
  language: en
```

**config-tv.yml**
```
collections:
  A&E:
    collection_order: alpha
    tmdb_network: 129
plex:
  library: TV Shows
  library_type: show
  sync_mode: sync
  token: removed
  url: http://192.168.4.46:32400
tmdb:
  apikey: removed
  language: en
```
