### ISSUE TITLE
Studio collections?!

### ISSUE THREAD

**Issue by samsepiol59** [mza921/Plex-Auto-Collections#12]
Hello everyone, I've been trying to get studio collections working but I can't seem to figure them out! 😩 anyone else tried it and succeeded? Thank you very much!

**Comment by burkasaurusrex** [comment]
Adding something like this to your `config.yml` should work

```yaml
    Pixar:
        studio: Pixar
        details:
            summary: A collection of Pixar movies
```

**Comment by samsepiol59** [comment]
Oh god, thanks so much @burkasaurusrex ! I have no idea what I was doing wrong before, but it works like a charm! Thank you again!

While I have you here, could I bug you with two more questions?
1) Is it possible to set a range of years to create a collection (eg, 1990-1999)?
2) could this project be used with TV or are the two libraries fundamentally different?

**Comment by burkasaurusrex** [comment]
>     1. Is it possible to set a range of years to create a collection (eg, 1990-1999)?

I'm not sure if either of these will work, but you can give it a try:
```yaml
1990s:
  decade: 1990
  details:
    summary: A collection of 1990s movies
```
or
```yaml
1990s:
  year: [1990,1991,1992,1993,1994,1995,1996,1997,1998,1999]
  details:
    summary: A collection of 1990s movies
````

>     2. could this project be used with TV or are the two libraries fundamentally different?
Some scaffolding is in place for this now, but I don't believe it's functional (it might work with Trakt lists)

**Comment by burkasaurusrex** [comment]
Just got around to testing this. It looks like this works:

> ```yaml
> 1990s:
>   year: [1990,1991,1992,1993,1994,1995,1996,1997,1998,1999]
>   details:
>     summary: A collection of 1990s movies
> ```

This also works (more yaml-y):
```yaml
2000s:
  year: 
    - 2000
    - 2001
    - 2002
    - 2003
    - 2004
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
  details:
    summary: A collection of 2000s movies
```

I'll add this to the readme / template and close this out
