### ISSUE TITLE
Script hangs on processing trakt-list

### ISSUE THREAD

**Issue by aga72** [mza921/Plex-Auto-Collections#13]
I have the script working on my home server but cannot get it to work on a remote server. I have tried nearly 10 different configurations and just cannot figure out what is wrong.

Here is my current config:

```
collections:
  Musicals:
    trakt-list: https://trakt.tv/users/asterlea/lists/top-musicals
    details:
      summary: blah blah blah
plex:
  library: MoviesTest
  library_type: movie
  token: ##############
  url: http://178.30.148.206:32400
radarr:
  url: http://127.0.0.1:12110/radarr/
  token: ##############
  quality_profile_id: 2
  root_folder_path: /home/username
  search: false
tmdb:
  apikey: ##############
  language: en
trakt:
  client_id: ##############
  client_secret: ##############
  # Below is filled in automatically when the script is run
  authorization:
    access_token: ##############
    token_type: Bearer
    expires_in: 7776000
    refresh_token: ##############
    scope: public
    created_at: 1592012620
image-server:
  host: 127.0.0.1
  port: 12920
```

My Plex server is showing the following on it's remote access page:

Private: http://178.30.148.206:32400
Public: http://178.30.148.206:32400

^ They are the exact same and I'm wondering if that's causing an issue. That IP is made up.
