### ISSUE TITLE
[Feature Request] Plex_search Critic / Audience rating

### ISSUE THREAD

**Issue by SerinitySW** [mza921/Plex-Auto-Collections#134]
It would be super cool to be able to make collections based on critic or audience rating. For example:

```
      Garbage:
            plex_search:
                     critic_rating: 0-40
                     audience_rating: 0-40
```
