### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by mouzzampk2014** [mza921/Plex-Auto-Collections#135]
Hi, not sure how to fix this. I am running in docker
```
|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.4.7
| Locating config...
| Using /config/config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| trakt attribute not found
|===================================================================================================|
| radarr attribute not found
|===================================================================================================|
| Locating Image Server...
| Posters Directory: ../config/posters not found
| Backgrounds Directory: ../config/backgrounds not found
| Images Directory: ../config/images not found
|===================================================================================================|
| 
Traceback (most recent call last):
  File "/app/plex_auto_collections.py", line 837, in <module>
    if input("| \n| Update Collections from Config? (y/n): ").upper() == "Y":
EOFError: EOF when reading a line
```
And here is my compose
```
  plex-auto-collections:
    image: burkasaurusrex/plex-auto-collections
    hostname: ${DOCKERHOSTNAME}
    container_name: plex-auto-collections
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex-auto-collections:/config
```
Tried different things but don't know what's going on, could you look into this.

Thank you

**Comment by burkasaurusrex** [comment]
Try switching the docker repo to `mza921/plex-auto-collections'

**Comment by mouzzampk2014** [comment]
Hi @burkasaurusrex I changed the image but same output 
```
|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.6.0
| Locating config...
| Using /config/config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| trakt attribute not found
|===================================================================================================|
| radarr attribute not found
|===================================================================================================|
| Locating Image Server...
| Posters Directory: ../config/posters not found
| Backgrounds Directory: ../config/backgrounds not found
| Images Directory: ../config/images not found
|===================================================================================================|
| 
Traceback (most recent call last):
  File "/app/plex_auto_collections.py", line 994, in <module>
    if input("| \n| Update Collections from Config? (y/n): ").upper() == "Y":
EOFError: EOF when reading a line
| Update Collections from Config? (y/n):
```
Here is my config.yml
```
collections:
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
plex:
  library: Movies
  library_type: movie ### 'movie' or 'show' ###
  token: vxCVw8KsCzv
  url: http://192.168.1.165:32400
  sync_mode: append
tmdb:
  apikey: 4acac3e0288
  language: en
tautulli:
  url: http://192.168.1.89:8181
  apikey: bb4d8394b
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```

**Comment by mouzzampk2014** [comment]
I only get this error when I place the config.yml

**Comment by burkasaurusrex** [comment]
What happens if you run it with the `--update` flag?

**Comment by burkasaurusrex** [comment]
Also, the following should be deleted:
```yaml
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
```

**Comment by mouzzampk2014** [comment]
> What happens if you run it with the `--update` flag?

I'm not sure how to run with `--update` in docker?

**Comment by burkasaurusrex** [comment]
> > What happens if you run it with the `--update` flag?
> 
> I'm not sure how to run with `--update` in docker?

You should be able to add `command: --update` to your docker compose

**Comment by mouzzampk2014** [comment]
Oh yes @burkasaurusrex its working perfectly fine after adding `command: --update`. 

Could you please help me out how to validate trakt authentication.

This is my config.yml now
```
collections:
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
plex:
  library: Films
  library_type: movie ### 'movie' or 'show' ###
  token: vxCVw8KsCzv
  url: http://192.168.1.165:32400
  sync_mode: append
tmdb:
  apikey: 4acac3e0288
  language: en
tautulli:
  url: http://192.168.1.89:8181
  apikey: bb4d8394b
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```
Thanks

**Comment by mouzzampk2014** [comment]
I get this when I run it with or without `--update`

```
docker exec -it plex-auto-collections python plex_auto_collections.py
Error response from daemon: Container 5418e9bbc4279f7310a58cecf024097a1f9e95e58ea5ba09afee7a4eea6c78d9 is restarting, wait until the container is running
```

**Comment by mouzzampk2014** [comment]
Hi, I did few more bits. 

This is my config.yml 
```
collections:
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
plex:
  library: Films
  library_type: movie ### 'movie' or 'show' ###
  token: 4acac3e0288
  url: http://192.168.1.165:32400
  sync_mode: append
tmdb:
  apikey: 4acac3e0288
  language: en
tautulli:
  url: http://192.168.1.89:8181
  apikey: 4acac3e0288
trakt:
  client_id: 4acac3e0288
  client_secret: 4acac3e0288
  auto_refresh_token: true
  authorization:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```
I get this output 
```
|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.6.0
| Locating config...
| Using /config/config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| Connecting to Trakt...
| Navigate to: https://trakt.tv/oauth/authorize?client_id=4acac3e0288&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code
| If you get an OAuth error your client_id or client_secret is invalid
Traceback (most recent call last):
  File "/app/plex_auto_collections.py", line 990, in <module>
    config = Config(config_path)
  File "/app/config_tools.py", line 110, in __init__
    TraktClient(config_path)
  File "/app/config_tools.py", line 376, in __init__
    self.updated_authorization = trakt_helpers.authenticate(self.authorization)
  File "/app/trakt_helpers.py", line 16, in authenticate
    code = six.moves.input('| trakt pin (case insensitive): ')
EOFError: EOF when reading a line
```
I am out of ideas now :)
