### ISSUE TITLE
Using multiple filters functions as OR not AND

### ISSUE THREAD

**Issue by CHINCB** [mza921/Plex-Auto-Collections#154]
Using the example below I am getting a collection containing any movie that has the genre war OR history instead of the expected war AND history

collections:
  War:
    all: true
    plex_search:
      genre: War
    filters:
      genre: History
    sync_mode: sync

**Comment by bigdork** [comment]
I think this will do what you want. Filters are used for ANDs

collections:
  War:
    genre: [War, History]
    sync_mode: sync

**Comment by mza921** [comment]
Try this:

```
collections:
  War:
    plex_search:
      genre: War
    filters:
      genre: History
    sync_mode: sync
```
