### ISSUE TITLE
tmdb_discover not obeying certification parameter

### ISSUE THREAD

**Issue by tehniemer** [mza921/Plex-Auto-Collections#160]
I have set up a kids movie collection based on the `tmdb_discover` and `certification` parameters, but the certification limit is not being obeyed. This is my config

```
    20 Most Popular Kids Movies:
        tmdb_discover:
            limit: 20
            certification_country: US
            certification.lte: PG
            sort_by: popularity.desc
        sync_mode: sync
        add_to_radarr: true
```

and this is a screenshot of the collection that is created. Not many of those are `G` or `PG`

![image](https://user-images.githubusercontent.com/11021632/103425775-517a6080-4b7a-11eb-918c-6d252bfdcc01.png)
