### ISSUE TITLE
Not ideal for big libraries

### ISSUE THREAD

**Issue by morganzero** [mza921/Plex-Auto-Collections#181]
First and foremost, good job on this script. However, with big libraries, it takes a long time to map the movies each time you run the script. Is there a way of saving the mapped movies to a database and only map new content?

**Comment by tehniemer** [comment]
Enable the `cache` option, that'll help.

**Comment by LeendertPlas** [comment]
what is this cache option? i don't see it in the readme

**Comment by tehniemer** [comment]
Interesting, it used to be in there, I don't know what happened to it. Take a look at my config in [#161](https://github.com/mza921/Plex-Auto-Collections/discussions/161)  to see how it's used.

**Comment by LeendertPlas** [comment]
Thank you, but i don't see any reference to a cache in your config in [message](https://github.com/mza921/Plex-Auto-Collections/discussions/161#discussion-1243925). Is that correct?

**Comment by tehniemer** [comment]
Shoot, forgot I redacted my Plex config in that. I can look at the context for you when I get home tonight.

**Comment by morganzero** [comment]
> Shoot, forgot I redacted my Plex config in that. I can look at the context for you when I get home tonight.

That'd be awesome! Looking forward to see if that'd help me.

**Comment by tehniemer** [comment]
This is how you use `cache`
```
plex:
    library: Movies
    library_type: movie ### 'movie' or 'show' ###
    token: 
    url:  
    sync_mode: append
    cache: true
    cache_update_interval: 60
```
