### ISSUE TITLE
Naming collections a certain name causes an error.

### ISSUE THREAD

**Issue by LeendertPlas** [mza921/Plex-Auto-Collections#189]
Naming a collection 'Animation' Will result in an error:

`| Updating collection: Animation...
| Sync Mode: sync
Traceback (most recent call last):
  File "C:\Plex\Plex-Auto-Collections-master\app\plex_auto_collections.py", line 1026, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "C:\Plex\Plex-Auto-Collections-master\app\plex_auto_collections.py", line 318, in update_from_config
    for item in plex_collection.children:
AttributeError: 'NoneType' object has no attribute 'children'`

Then, changing the name to 'Animation Movies' will prevent this error.

`| Updating collection: Animation Movies...
| Sync Mode: sync
| Config Error: Collection Animation Movies Not Found
|`

I have no idea why, as it should not be related to naming it after a genre as 'Action' does work. The same behaviour can be seen by adding a collection 'War', which results in an error and 'War movies' which does not.

The config i used is:

```
collections:
############################
####       Genre        ####
############################
  Animation Movies: 
    imdb_list:
      - https://www.imdb.com/search/title/?title_type=feature,tv_movie&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=10000,&genres=animation&maxresult250
      - https://www.imdb.com/search/title/?title_type=feature,tv_movie&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=10000,&genres=animation&sort=user_rating,desc&maxresult250
      - https://www.imdb.com/list/ls027345371/
      - https://www.imdb.com/list/ls004803270/
    sync_mode: sync
    sort_title: "*000Animation"
    summary: Genre highlights as a mix of best rated, most popular, and special recommendations. Use *genre* filters in library view to see all movies of a specific genre 
  War Movies: 
    imdb_list:
      - https://www.imdb.com/search/title/?title_type=feature,tv_movie&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=10000,&genres=war&maxresult200
      - https://www.imdb.com/search/title/?title_type=feature,tv_movie&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=10000,&genres=war&sort=user_rating,desc&maxresult200
      - https://www.imdb.com/list/ls021609968/
      - https://www.imdb.com/list/ls009678583/
    sort_title: "*000War"
    summary: Genre highlights as a mix of best rated, most popular, and special recommendations. Use *genre* filters in library view to see all movies of a specific genre
```
