### ISSUE TITLE
Feature Request : Meta Collection Definition 

### ISSUE THREAD

**Issue by delegreg** [mza921/Plex-Auto-Collections#216]
Hi, and first thank you for continuing work on this great concept.

Here is my use case : 

As a plex autocollection user, i would like to be able to define a way to create "meta" collections in a given library.

First example : 

- For a movie library that is called "Favorite directors"
- Lirary contains proper metadata for films 
- I create a definition like this : 

```
collections:
  Meta_Collection_Definition_1:
    plex_meta:
      aggregate_type: director
      naming: director.name
      summary: director.bio
      poster: director.photo
```
- Meaning : find all directors in current library, create one collection for each distinct director in all movies metadata, giving it the director's name for collection name, his photo as poster and the director's bio as summary, then assign movies who match the director to the created collections.

Second Example : 

- For a movie library that is called "Favorite genres"
- I may create a definition like this : 

```
collections:
  Meta_Collection_Definition_2:
    plex_meta:
      aggregate_type: genre
      naming: genre
      summary: ./{genre}.txt
      poster: ./{genre}-poster.png
```
- Meaning : find all genres in current library, create one collection for each distinct genre in all movies metadata, giving it the genre's name for collection name, then use the genre in a filename pattern to find summary and poster files, then assign movies who match the genre to the created collections.

Ideally, if you can handle multiple meta definitions or composite aggregates (director + lead actor or genre + decade) that is a plus.
