### ISSUE TITLE
x missing movies from Trakt List: 

### ISSUE THREAD

**Issue by pekempy** [mza921/Plex-Auto-Collections#221]
Hey, I've double and triple checked my plex token/library setup, as well as radarr token/setup.

It's checking and finding the number of movies in the trakt list, but it's saying they're all missing from my library.

I'm using the newer "Plex Movie" agent - I've tried with IP, 127.0.0.1 and localhost for the URLS and all of them get the same.

Any ideas what could be going wrong?

```
plex:
   library: Films
   library_type: movie
   token: [redacted]
   url: http://192.168.1.235:32400
   sync_mode: append
radarr:
   url: http://192.168.1.235:7878/radarr
   token: [redacted]
   quality_profile_id: 4
   root_folder_path: /Movies/
   search: true
tmdb:
   apikey: [redacted]
   language: en
trakt:
   client_id: [redacted]
   client_secret: [redacted]
  # Below is filled in automatically when the script is run
   authorization:
      access_token: [redacted]
      token_type: Bearer
      expires_in: 7889237
      refresh_token: [redacted]
      scope: public
      created_at: 1616432508
```

![image](https://user-images.githubusercontent.com/22874875/113283835-b6ac3200-92e0-11eb-8509-f3be73b211f5.png)

Output ends up being the below but for all collections

```
==================================================================
 Plex Auto Collections by /u/iRawrz
==================================================================
Attempting to start image server
IMAGE SERVER RUNNING ON http://127.0.0.1:5000/images/
Updating collection: Exorcist...
Processing trakt-list: https://trakt.tv/users/gersomuzziel/lists/the-exorcist
6 missing movies from Trakt List: https://trakt.tv/users/gersomuzziel/lists/the-exorcist
Updating collection: Batman...
Processing trakt-list: https://trakt.tv/users/movistapp/lists/batman
9 missing movies from Trakt List: https://trakt.tv/users/movistapp/lists/batman
Updating collection: Expendables...
Processing trakt-list: https://trakt.tv/users/ireallylovevids/lists/expendables
3 missing movies from Trakt List: https://trakt.tv/users/ireallylovevids/lists/expendables
```
