### ISSUE TITLE
Summary no longer being set.

### ISSUE THREAD

**Issue by JourneyOver** [mza921/Plex-Auto-Collections#27]
Script no longer sets the summary. I've tried both `tmdb-summary` with the correct collections page's ID and I've tried the normal `summary` with the summary text after, doing either sets the summary temporarily but upon doing anything in plex (going to a different movie or show or to the home page / clicking the edit button for the movie / etc) or exiting the script it removes the summary from the collection.

I am running plex version `1.20.0.3125` but this has been going on for several versions now.

**Comment by burkasaurusrex** [comment]
yea, if you don't mind splitting the issues, that would be helpful

**Comment by JourneyOver** [comment]
Done @burkasaurusrex .. sorry it took 3 hours to get back to this, quickly whipped this up right before I had to leave for work.

**Comment by burkasaurusrex** [comment]
Thanks. Do you mind running `pip show tmdbv3api` and posting the output here?

**Comment by JourneyOver** [comment]
```
Name: tmdbv3api
Version: 1.5.1
Summary: A lightweight Python library for The Movie Database (TMDb) API.
Home-page: https://github.com/AnthonyBloomer/tmdbv3api
Author: Anthony Bloomer
Author-email: ant0@protonmail.ch
License: MIT
Location: c:\tools\python3\lib\site-packages
Requires: requests
Required-by:
```

**Comment by burkasaurusrex** [comment]
Yea, might be the python version - can you test on `3.7.x`? Alternatively, if you want to give the docker a try here: https://hub.docker.com/r/burkasaurusrex/plex-auto-collections

**Comment by burkasaurusrex** [comment]
Actually, I'm using `3.8` on Windows right now without any problem. Do you mind sharing the relevant snippet of YAML?

**Comment by JourneyOver** [comment]
Two examples:

```
collections:
  47 Meters Down:
    tmdb-list: https://www.themoviedb.org/collection/635922
    details:
      tmdb-summary: 635922
```
doesn't work and

```
collections:
  47 Meters Down:
    tmdb-list: https://www.themoviedb.org/collection/635922
    details:
      summary: A series of survival horror films, where the plot is based on surviving and escaping sharks.
```
doesn't work

They both temporarily set the summary, but upon exiting the script or doing anything in plex the summary disappears.
