### ISSUE TITLE
To do: refresh Trakt token on each run

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#50]
Trakt provides the ability to [refresh](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token) the Trakt token. Seems like the script should refresh the token on each run or on some interval (maybe set the interval in the yaml with a logical default) to avoid auth silently failing? I've come across the issue myself given that Trakt tokens expire every 3 months.

Looks like #14 and #48 are probably both caused by this.

**Comment by meisnate12** [comment]
at around line 216 in config_tools.py I have this 

                def check_trakt (auth):
                    try:
                        #TODO: Validate Trakt Connection
                        return True
                    except:
                        return False

I was having problems figuring out a way to validate the credentials. If we can test right here to see if it fails somehow it should try to reauthenticate on start-up. If you have any idea how to validate it we should be good to go

**Comment by burkasaurusrex** [comment]
I would probably test by retrieving the [user's settings](https://trakt.docs.apiary.io/#reference/users/settings/retrieve-settings)? As long as that request returns a `200` instead of a `403`, then auth should work. Here's the [full list of status codes](https://trakt.docs.apiary.io/#introduction/status-codes).

I don't know trakt.py but seems like `Trakt['users/settings'].get()` or `Trakt.['users'].settings()` or something might be workable. Not sure if there's a way to force trakt.py to surface http status codes or not.

**Comment by burkasaurusrex** [comment]
Or I guess you wouldn't have to worry about the http status codes - you could just test whether that API call return an expected settings object or not.

**Comment by mza921** [comment]
I was using https://github.com/fuzeman/trakt.py/blob/master/tests/oauth/test_oauth.py as a reference for this and thought the `refresh=true` from https://github.com/mza921/Plex-Auto-Collections/blob/dda8dc9374b18103a5ee7c3d689e1afda080ffcd/app/trakt_helpers.py#L14 would have covered it. Looks like I'm missing something.

**Comment by meisnate12** [comment]
this can be closed now

**Comment by burkasaurusrex** [comment]
Not sure this is ready to be closed? I'll take a look this week but basically the script would pass the `refresh_token` back to Trakt to get a renewed authentication. The renewed authentication would need to overwrite the existing YAML authentication.

**Comment by meisnate12** [comment]
ok I see what you're saying I thought you meant us telling the program to validate and refresh on startup I can look into this cause it sounds way better lol

**Comment by mza921** [comment]
I've tested the token refresh and have it working in a different [branch](https://github.com/mza921/Plex-Auto-Collections/tree/trakt-refresh). One problem I encountered is that the refresh token can only be used once, so if multiple config files share the same tokens, the other config files break. To make it worse, if execution is automated with `--update`, the user might not notice that the script is failing for the particular config file (and will probably run into #102). This makes a good case for #78 and separating the authorization configs.

**Comment by meisnate12** [comment]
I like the format I have in this [comment](https://github.com/mza921/Plex-Auto-Collections/issues/78#issuecomment-720882438) and think being able to run multiple config files would be beneficial

**Comment by burkasaurusrex** [comment]
For now, what about just creating a setting on whether to refresh the token or not?

Agreed that we need to find a better way to separate auth from config. It's going to be tricky though since there are so many settings that may be different for each set of collections. For example, in your comment @meisnate12, how would I set one set of collections to sync while the other set appends?

**Comment by meisnate12** [comment]
I was thinking of having sync_mode net setable at the global level, library level, and collection level

**Comment by mza921** [comment]
__config.yml__
```
plex:
  token: ###################
  url: http://192.168.1.5:32400
radarr:
  url: http://192.168.1.5:7878/radarr/
  token: ###########################
  quality_profile_id: 4
  root_folder_path: /mnt/user/PlexMedia/movies
  add_movie: false
  search_movie: false
tmdb:
  apikey: ############################
  language: en
tautulli:
  url: http://192.168.1.5:8181
  apikey: ############################
trakt:
  client_id: ############################
  client_secret: ############################
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```
The configuration for the collections can be in a separate directory (similar to Plex-Python-Libraries' _recipes_). They will either have to be called out individually as arguments or the script can just iterate through everything in the collections directory.

__collections/movies.yml__
```
collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
plex:
  library: Movies
  library_type: movie
  sync_mode: append
```
__collections/movies-4k.yml__
```
collections:
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
  Pixar:
    studio: Pixar
    summary: A collection of Pixar movies
    sort_title: *Pixar
    content_rating: G
    collection_mode: show_items
    collection_order: alpha
plex:
  library: Movies - 4K
  library_type: movie
  sync_mode: append
```
__collections/tv.yml__
```
collections:
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
plex:
  library: TV Shows
  library_type: show
  sync_mode: append
```

**Comment by meisnate12** [comment]
To make it easier to find the library files I was saying we have the settings all in the config file and just the collections in their own like below. This will let us not have to do so much checking in the file system of each file to see if it is a collection file. We can just check and see if the file the user specified exists vs having to check all the files around the program and it allows users to put library files wherever they want. 


**config.yml**

```
plex:
  libraries:
    Movies:    #Library Name
      library_config_path: /movie_collection.yml
      library_type: movie
      sync_mode: append
    Movies - 4K
      library_config_path: /4kmovie_collection.yml
      library_type: movie
      sync_mode: append
    TV Shows:    #Library Name
      library_config_path: /show_collection.yml
      library_type: show
      sync_mode: append
  token: ###################
  url: http://192.168.1.5:32400
radarr:
  url: http://192.168.1.5:7878/radarr/
  token: ###########################
  quality_profile_id: 4
  root_folder_path: /mnt/user/PlexMedia/movies
  add_movie: false
  search_movie: false
tmdb:
  apikey: ############################
  language: en
tautulli:
  url: http://192.168.1.5:8181
  apikey: ############################
trakt:
  client_id: ############################
  client_secret: ############################
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```

**movie_collection.yml**

```
collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Most Popular Movies (30 Days):
    sync_mode: sync
    collection_mode: show_items
    tautulli:
      list_type: popular
      list_days: 30
      list_size: 10
```

**4kmovie_collection.yml**

```
collections:
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
  Pixar:
    studio: Pixar
    summary: A collection of Pixar movies
    sort_title: *Pixar
    content_rating: G
    collection_mode: show_items
    collection_order: alpha
```

**show_collection.yml**

```
collections:
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
```

**Comment by mza921** [comment]
I think the library belongs in the collection file. What if I don't want a list applied against a certain library, or if the list isn't applicable to a library type? Or what if I name a movie library and tv library the same thing? Plex allows this, but then you'd have duplicate keys in under `libraries:`

**Comment by meisnate12** [comment]
> What if I don't want a list applied against a certain library, 

im not really sure what your asking/ how its any different from now?

> or if the list isn't applicable to a library type?

it wont run lists it cant same as it does now when they're in the same file

> Or what if I name a movie library and tv library the same thing?

Thats a good point i guess we would have to have a show_library attribute and movie_library attribute which would also allow us to get rid of having the user specify which library_type. this is all of course if we went with my design 

```
plex:
  movie_libraries:
    Movies:    #Library Name
      library_config_path: /movie_collection.yml
      sync_mode: append
    Movies - 4K
      library_config_path: /4kmovie_collection.yml
      sync_mode: append
  show_libraries:
    TV Shows:    #Library Name
      library_config_path: /show_collection.yml
      sync_mode: append
  token: ###################
  url: http://192.168.1.5:32400
```

> I think the library belongs in the collection file. 

If you want the plex attribute in each file thats fine but we should still have a list of files in the config like this 

```
plex:
  libraries:
      - /movie_collection.yml
      - /4kmovie_collection.yml
      - /show_collection.yml
  token: ###################
  url: http://192.168.1.5:32400
```
