### ISSUE TITLE
Docker image is out of date

### ISSUE THREAD

**Issue by tehniemer** [mza921/Plex-Auto-Collections#55]
I'm able to use the docker image to create collections based on PLEX atributes like `genre`, `actors`, or `studio`, but no collections that use lists are being created. This is all I see in the logs.

```
Updating collection: Jurassic Park...,
Processing tmdb_list: https://www.themoviedb.org/collection/328,
Updating collection: Alien (Past & Present)...,
Processing tmdb_list: https://www.themoviedb.org/collection/8091,
Processing tmdb_list: https://www.themoviedb.org/collection/135416,
Updating collection: James Bond...,
Processing tmdb_list: https://www.themoviedb.org/collection/645,
Updating collection: Star Wars...,
Processing tmdb_list: https://www.themoviedb.org/collection/10,
Updating collection: Star Trek (Alternate Reality)...,
Processing tmdb_list: https://www.themoviedb.org/collection/115575,
Updating collection: IMDb Top 250...,
Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250,
Updating collection: Christmas...,
Processing trakt_list: https://trakt.tv/users/movistapp/lists/christmas-movies,
Processing trakt_list: https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza,
Updating collection: Reddit Top 250 (2019)...,
Processing trakt_list: https://trakt.tv/users/jay-greene/lists/reddit-top-250-2019-edition
```

Another thing to mention is that this works
```
  Dave Chappelle:
    actors: Dave Chappelle
#    tmdb_summary: 4169
```
and this fails with an exit code 1
```
  Dave Chappelle:
    actors: Dave Chappelle
    tmdb_summary: 4169
```

**Comment by tehniemer** [comment]
This is an error I've been seeing a lot that I don't understand. 
```
  File "plex_auto_collections.py", line 378, in <module>,
    update_from_config(config_path, plex, True),
  File "plex_auto_collections.py", line 44, in update_from_config,
    values = collections[c][m].split(", "),
AttributeError: 'int' object has no attribute 'split'
```

**Comment by tehniemer** [comment]
Here's my sanitized `config.yml`
```
collections:
  Jurassic Park:
    tmdb_list: https://www.themoviedb.org/collection/328

  Alien (Past & Present):
    tmdb_list:
      - https://www.themoviedb.org/collection/8091
      - https://www.themoviedb.org/collection/135416

  James Bond:
    tmdb_list: https://www.themoviedb.org/collection/645

  Star Wars:
    tmdb_list: https://www.themoviedb.org/collection/10

  Star Trek (Alternate Reality):
    tmdb_list: https://www.themoviedb.org/collection/115575

  Marvel Cinematic Universe:
    trakt_list: https://trakt.tv/users/movistapp/lists/marvel

  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250

  Christmas:
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza

  Reddit Top 250 (2019):
    trakt_list: https://trakt.tv/users/jay-greene/lists/reddit-top-250-2019-edition

  Documentaries:
    genres: Documentary
    summary: A collection Documentaries

  Dave Chappelle:
    actors: Dave Chappelle

  Pixar:
    studio: Pixar
    summary: A collection of Pixar movies
    collection_mode: show_items
    collection_sort: alpha
    
  Studio Ghibli:
    studio: Studio Ghibli
    collection_mode: show_items
    collection_sort: alpha
    
  90s Movies:
    year:
      - 1990
      - 1991
      - 1992
      - 1993
      - 1994
      - 1995
      - 1996
      - 1997
      - 1998
      - 1999

plex:
  library: Movies
  library_type: movie ### 'movie' or 'show' ###
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  url: http://192.168.29.11:32400

radarr:
  url: radarr:7878
  version: v3
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  quality_profile_id: 1
  root_folder_path: /data/multimedia/Movies
  add_movie: false
  search_movie: false

tmdb:
  apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  language: en

trakt:
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

image_server:
  poster_directory: /config/posters
  background_directory: /config/backgrounds
  image_directory: /config/images
```
