### ISSUE TITLE
Support OMBI requests

### ISSUE THREAD

**Issue by mza921** [mza921/Plex-Auto-Collections#62]
Create collections based on a OMBI users' requests. Something like:
```
collections:
  mza's requests:
    ombi_movies: <ombi username>    (or ombi_tv)
ombi:
  url:
  apikey:
```
