### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by hacktek** [mza921/Plex-Auto-Collections#88]
I can't get it to work using the sample config file.

```
| Version 2.3.1
| Locating config...
| Using /config/config.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| tmdb attribute not found
|===================================================================================================|
| tautulli attribute not found
|===================================================================================================|
| Connecting to Trakt...
| Stored Authorization Failed
| Navigate to: https://trakt.tv/oauth/authorize?client_id=xxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code
| If you get an OAuth error your client_id or client_secret is invalid
| trakt pin (case insensitive): Traceback (most recent call last):
  File "/app/plex_auto_collections.py", line 650, in <module>
    config = Config(config_path)
  File "/app/config_tools.py", line 110, in __init__
    TraktClient(config_path)
  File "/app/config_tools.py", line 366, in __init__
    self.updated_authorization = trakt_helpers.authenticate(self.authorization)
  File "/app/trakt_helpers.py", line 16, in authenticate
    code = six.moves.input('| trakt pin (case insensitive): ')
EOFError: EOF when reading a line
```

config.yml:

```
collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sync_mode: sync
    collection_mode: show_items
  Marvel:
    trakt_list: https://trakt.tv/users/movistapp/lists/marvel
    collection_mode: show_items
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
plex:
  library: Movies
  library_type: movie
  token: xxxx
  url: https://plex.domain.tld:443
  sync_mode: append
trakt:
  client_id: xxx
  client_secret: xxx
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images
```
