### ISSUE TITLE
Crashing on specific TV Series 

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#89]
Playing with creating collections based on TV service, and I've got a show I'm calling out specifically with `tmdb_show:` but the script is crashing.

I've changed the ID order around, even running with just the one ID, it crashes every time.

The show is "Chip and Potato" ... which is thrilling, I know.
https://www.themoviedb.org/tv/89504-chip-and-potato

Config:
```
Netflix:
    sort_title: -3 Netflix
    summary: A collection of original TV Shows from the Netflix streaming service
    sync_mode: append
    collection_order: alpha
    #studio: Netflix
    tmdb_show: [72615, 59717, 44305, 89504, 64421]
```

Output:
```
| Updating collection: Netflix...
| Sync Mode: append
|
|
|
| Processing tmdb_show: 72615
| Netflix Collection | = | Alias Grace
|
| Processing tmdb_show: 59717
| Netflix Collection | = | Comedians in Cars Getting Coffee
|
| Processing tmdb_show: 44305
| Netflix Collection | = | Dragons
|
| Processing tmdb_show: 89504
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 814, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 445, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/home/pg/Plex-Auto-Collections/app/plex_tools.py", line 173, in add_to_collection
    shows, missing = imdb_tools.tmdb_get_shows(config_path, plex, value)
  File "/home/pg/Plex-Auto-Collections/app/imdb_tools.py", line 277, in tmdb_get_shows
    if int(p_tv_map[t]) == int(tvdb_id):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Output:
